clean quests sched
Pupitar/RDMAss pull request #16
Opened 2022-10-05 21:43 UTC by lenisko

Add ability to schedule quests clean action.

2022-10-05 21:44 UTC, lenisko commented
@Fabio1988 Here you go :) Please test.

2022-10-06 06:32 UTC, Fabio1988 requested changes

2022-10-06 06:32 UTC, Fabio1988 commented on rdmass/bot.py
> +            ra = RDMSetApi()
Do you need this RDMSetApi here? It's already part of new utils function called next line :)

2022-10-06 10:50 UTC, lenisko commented on rdmass/bot.py
> +            ra = RDMSetApi()
This class contains only class methods without any init method. Replaced to look "cleaner" :)

2022-10-06 22:31 UTC, merged